In [1]:
import requests
import pandas as pd
from IPython.display import display

In [39]:
def extract_from_api(country,n=-1):
     # initializing an error variable to 0

    err=0
    #print({country.lower().replace(' ','%20')})
    
    
    #  converting 'country' to lowercase and replacing spaces with %20 and sending the API request
    req = requests.get(f"http://universities.hipolabs.com/search?country={country.lower().replace(' ','%20')}") 
    
    # if status code != 200 error variable is assigned to 1
    if req.status_code!= 200:
        err = 1
    # Converting the request output in JSON format
    js = req.json() 

            

    try:    
        if err==1:
            # raises an exception in case of an error
            raise Exception()
        df = pd.DataFrame()

        for i in js[0].keys():
         
           # Converting/Structuring the JSON output into a data frame
            df[i] = [j[i] for j in js]
           # print(df[i])
    # Returning no data upon an error
    except:
        return "No Data Found" 
    else:
        if n!=-1:
            print("Number of rows:",len(df))
            return df.head(n) #returns top n records
        else:
            return df # returns the whole data frame if n=-1

In [40]:
extract_from_api("United States",10)

Number of rows: 2181

,web_pages,state-province,alpha_two_code,domains,country,name
0,[http://www.marywood.edu],None,US,[marywood.edu],United States,Marywood University
1,[http://www.lindenwood.edu/],None,US,[lindenwood.edu],United States,Lindenwood University
2,[https://sullivan.edu/],None,US,[sullivan.edu],United States,Sullivan University
3,[https://www.fscj.edu/],None,US,[fscj.edu],United States,Florida State College at Jacksonville
4,[https://www.xavier.edu/],None,US,[xavier.edu],United States,Xavier University
5,[https://home.tusculum.edu/],None,US,[tusculum.edu],United States,Tusculum College
6,[https://cst.edu/],None,US,[cst.edu],United States,Claremont School of Theology
7,[https://www.columbiasc.edu/],None,US,[columbiasc.edu],United States,Columbia College (SC)
8,[http://www.clpccd.edu/],None,US,[clpccd.edu],United States,Chabot-Las Positas Community College District
9,[https://www.keller.edu/],None,US,[keller.edu],United States,Keller Graduate School of Management

In [44]:
dataframe=extract_from_api("United States",-1)
dataframe.to_excel("univ_data.xlsx")